"""Paleta semântica Outono na Tundra, ajustada ao padrão visual do pico_tui."""

BG_ROOT = "#4A4036"
BG_PANEL = "#5E6650"
BG_WIDGET = "#3B3930"
BG_RAISED = "#514B40"
BG_SELECTED = "#6A604C"
BORDER_SOFT = "#7A7652"
BORDER_STRONG = "#938768"
TEXT_PRIMARY = "#E7DCC1"
TEXT_SECONDARY = "#C8BFA5"
TEXT_MUTED = "#A79D89"
TEXT_DIM = "#7C6F64"
TEXT_DISABLED = "#625E52"
TEXT_INVERSE = "#211E19"
ACCENT_FOCUS = "#B98743"
ACCENT_ACTION = "#B06D3E"
ACCENT_COPPER = "#A86148"
ACCENT_RUST = "#8C4A32"
ACCENT_LICHEN = "#7F855F"
ACCENT_PINE = "#4D6554"
STATE_OK = "#9AA77B"
STATE_INFO = "#6E9A92"
STATE_WARNING = "#C69A45"
STATE_DEGRADED = "#C36A43"
STATE_CRITICAL = "#8C4543"
STATE_OFFLINE = "#59616A"
STATE_UNKNOWN = "#735C72"
STATE_CHANGED = "#C3A87A"

# Aliases preservados para compatibilidade com o programa-base.
BG_BASE = BG_ROOT
CRITICAL = STATE_CRITICAL
BORDER_DIM = BORDER_SOFT
WARNING = STATE_WARNING
SUCCESS = STATE_OK
ACCENT2 = ACCENT_COPPER
ACCENT = ACCENT_FOCUS
TEXT_MAIN = TEXT_PRIMARY

STATUS_MARKERS = {
    "ONLINE": "[OK]",
    "AGING": "[INFO]",
    "STALE": "[STALE]",
    "LOST": "[LOST]",
    "OFFLINE": "[OFFLINE]",
    "UNKNOWN": "[N/A]",
}

QUALITY_MARKERS = {
    "REAL": "[REAL]",
    "SIMULATED": "[SIM]",
    "PLACEHOLDER": "[N/A]",
    "DEGRADED": "[DEG]",
    "INVALID": "[CRIT]",
    "STALE": "[STALE]",
    "LOST": "[LOST]",
    "UNKNOWN": "[N/A]",
}
